#!/bin/bash
echo "#!/bin/bash" >> betty
echo "# Simply a wrapper script to keep you from having to use betty-style" >> betty
echo "# and betty-doc separately on every item." >> betty
echo "# Originally by Tim Britton (@wintermanc3r), multiargument added by" >> betty
echo "# Larry Madeo (@hillmonkey)" >> betty
echo "" >> betty
echo "BIN_PATH="/usr/local/bin"" >> betty
echo "BETTY_STYLE="betty-style"" >> betty
echo "BETTY_DOC="betty-doc"" >> betty
echo "" >> betty
echo "if [ "$#" = "0" ]; then" >> betty
echo "    echo "No arguments passed."" >> betty
echo "    exit 1" >> betty
echo "fi" >> betty
echo "" >> betty
echo "for argument in "$@" ; do" >> betty
echo "    echo -e "\n========== $argument =========="" >> betty
echo "    ${BIN_PATH}/${BETTY_STYLE} "$argument" " >> betty
echo "    ${BIN_PATH}/${BETTY_DOC} "$argument"" >> betty
echo "done" >> betty
